package com.muni.seminarorganizer;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AttendeeUser implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public AttendeeUser() {
    }




}