package com.muni.seminarorganizer;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AttendeeUser implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label(value = "IdentityNumber")
	private java.lang.String identityNumber;

	public AttendeeUser() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getIdentityNumber() {
		return this.identityNumber;
	}

	public void setIdentityNumber(java.lang.String identityNumber) {
		this.identityNumber = identityNumber;
	}

	public AttendeeUser(java.lang.String name, java.lang.String identityNumber) {
		this.name = name;
		this.identityNumber = identityNumber;
	}

}