package com.muni.seminarorganizer;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CreditCardDetails implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Credit card number")
	private java.lang.String number;
	@org.kie.api.definition.type.Label(value = "Expiration")
	private java.lang.String expiration;
	@org.kie.api.definition.type.Label(value = "CVC")
	private java.lang.Integer cvc;

	public CreditCardDetails() {
	}

	public java.lang.String getNumber() {
		return this.number;
	}

	public void setNumber(java.lang.String number) {
		this.number = number;
	}

	public java.lang.String getExpiration() {
		return this.expiration;
	}

	public void setExpiration(java.lang.String expiration) {
		this.expiration = expiration;
	}

	public java.lang.Integer getCvc() {
		return this.cvc;
	}

	public void setCvc(java.lang.Integer cvc) {
		this.cvc = cvc;
	}

	public CreditCardDetails(java.lang.String number,
			java.lang.String expiration, java.lang.Integer cvc) {
		this.number = number;
		this.expiration = expiration;
		this.cvc = cvc;
	}

}