package com.muni.seminarorganizer;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.xml.bind.annotation.XmlRootElement
public class Lecture implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label(value = "Information")
	private java.lang.String information;

	public Lecture() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getInformation() {
		return this.information;
	}

	public void setInformation(java.lang.String information) {
		this.information = information;
	}

	public Lecture(java.lang.String name, java.lang.String information) {
		this.name = name;
		this.information = information;
	}

}