package com.muni.seminarorganizer;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.xml.bind.annotation.XmlRootElement
public class OrganizerUser implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label("IdentityNumber")
	private java.lang.String identityNumber;

	public OrganizerUser() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getIdentityNumber() {
		return this.identityNumber;
	}

	public void setIdentityNumber(java.lang.String identityNumber) {
		this.identityNumber = identityNumber;
	}

	public OrganizerUser(java.lang.String name, java.lang.String identityNumber) {
		this.name = name;
		this.identityNumber = identityNumber;
	}

}